name: DEPLOYMENT

on:
  push:
    branches: [ "deployment/docker" ]
  pull_request:
    branches: [ "deployment/docker" ]
  workflow_dispatch:
  
jobs:
  Th_to_DockerHub:
        name: Talenthunters to DockerHub
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        if: "contains(github.event.commits[0].message, '[deploy]')"

        steps:
          - name: checkout repo
            uses: actions/checkout@v2

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            uses: docker/login-action@v1
            with:
              username: devoncarswell
              password: dckr_pat_wf7PjS6Fn8170p986gNRSH3yYW8

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: TalentHunters/TalentHunters-BackEnd/Dockerfile
              push: true
              tags: devoncarswell/talenthunters:latest

          - name: Run the image in a container
            uses: addnab/docker-run-action@v3
            with:
              image: devoncarswell/talenthunters:latest
              run: |
                echo "runing the docker image"
                
 